theme: jekyll-theme-minimal
title: Metabolomics-tutorial
description: "Tutorial for metabolomics data analysis, derived from the tutorial by Mendez et al. (2019) DOI: 10.1007/s11306-019-1588-0"
show_downloads: True
dependencies:
- python=3.7.3
- jupyter=1.0.0
- matplotlib=3.0.3
- numpy=1.16.3
- pandas=0.24.2
- scikit-learn=0.21.1
- seaborn=0.9.0
- xlrd=1.2.0
