name: MetabWorkflowTutorial
channels:
  - defaults
  - conda-forge
  - cimcb
dependencies:
  - python=3.7.3
  - beakerx=1.3.0
  - bokeh=1.1.0
  - numpy=1.16.3
  - pandas=0.24.2
  - openpyxl=2.6.1
  - cimcb_lite=1.0.0
  - tornado=5.1.1
  - matplotlib=3.0.3
  - scikit-learn=0.21.1
  - seaborn=0.9.0
  - xlrd=1.2.0
  - pheatmap_1.0.12
  - magrittr_1.5*
  - pander_0.6.3        
  - RColorBrewer_1.1-2
  - multtest_2.42.0
  - msdata_0.26.0    
  - xcms_3.8.2
  - MSnbase_2.12.0 
  - ProtGenerics_1.18.0 
  - S4Vectors_0.24.4     
  - mzR_2.20.0           
  - Rcpp_1.0.5          
  - BiocParallel_1.20.1  
  - Biobase_2.46.0       
  - BiocGenerics_0.32.0 
  - scatterplot3d_0.3-41 
  - ggplot2_3.3.2   
